### ISSUE TITLE
Favorite Headers

### ISSUE THREAD

**Issue by mastacheata** [odin-public/RESTClient-APS#44] opened 2016-06-28 22:45 UTC
Currently one can STORE favorite headers, but not use them in any way.
I'd like to add that functionality. Is there any preferred layout for that?
At first I thought about adding the favorites as additional menu items to the Headers Menu, but that could easily get too much, so I'm now preferring a modal window like the "Show All Bookmarks" thing.
Any input is appreciated. I'll probably play with that tomorrow evening.

**Comment by mastacheata** [comment] 2016-07-01 00:58
Strange thing is: Storing and Using works just fine if I build this myself and try it in FF-dev
Using the version from AMO in FF-stable doesn't update the favorite header list at all.

Any ideas on what might cause this?

**Comment by gear54rus** [comment] 2016-07-04 11:33
I think I missed that 'favorite header' part entirely. It never quite clicked with me that there's a gap there (can save but can't load)...

I have no idea what the problem is there (and I think there is no such table in SQLite?) and will most likely accept any solution. The best way probably would be to place them in the same menu (in place where mouse is): https://i.imgur.com/7gp8oJc.png since they are representable fairly easily (truncation needs to be implemented for long values).

**Comment by mastacheata** [comment] 2016-07-04 12:43
The headers are not stored in the SQLite DB, but in the Preferences file of the addon.
`var favoriteHeaders = restclient.getPref('favoriteHeaders', '');
restclient.setPref('favoriteHeaders', JSON.stringify(favoriteHeaders));
restclient.main.updateFavoriteHeadersMenu();`
(This is just an excerpt from the code, there's more stoff happening between the first and second line)

It's already there and should in fact look like this: https://1drv.ms/i/s!AmVzL4VsG04hkpsFOmB--M6SwMT_zA
I've got no idea what I did to make it work, but in my automated builds this is working perfectly fine.
I'm pretty sure I didn't touch any of that functionality in my PRs so far.

**Comment by gear54rus** [comment] 2016-07-13 12:01
I could not reproduce that. Can you please supply exact steps and the commit I have to do them on?

**Comment by mastacheata** [comment] 2016-07-13 12:52
The problem exists in the 1.8 Release as published to AMO and on the Github Releases.

Steps to reproduce:
1. Open RestClient
2. Click Headers -> Custom Header
3. Fill out both Name and Value
4. Check the Save to favorites box
5. Click okay
6. The header appears correctly in the Headers Table/as header tag (depending on your settings)
7. The headers Dropdown has no (or at least not the new favorite) headers
8. Restarting doesn't change anything about it (no idea why I thought it would)

I assume this is working in my dev-builds due to the checkbox fixes I implemented. (It was reading the default checked attribute instead of the actual current checked state)

**Comment by gear54rus** [comment] 2016-07-18 07:11
Well yeah, I've merged `checkboxes` and `jjsonviewer` just recently in 910e1e011fa263ec76ca44838f7da5dd755c5e52 and it appears that headers are working (you can save, restore and clear them). Are we going to say that this is fixed or did you have some more ideas in mind?

**Comment by mastacheata** [comment] 2016-07-18 12:29
I thought about making all the favorites look the same, but after getting the "original" header bookmarks back, I'm starting to think that my idea would be way too much. 

So from my point, we can consider this solved. 
Thank you (and your employer) very much for incorporating my changes, despite not being related to your core products at all. 
-- 
Gruß, 
Benedikt Bauer 

Am 18. Juli 2016 09:11:27 MESZ, schrieb Paul <notifications@github.com>:

**Comment by gear54rus** [comment] 2016-07-19 04:42
Fixed somewhere in 910e1e011fa263ec76ca44838f7da5dd755c5e52 or 6fc61f2912e3c8e82c4f70ab8597182b8593d173 :smile:

**Closed by gear54rus** 2016-07-19 04:42 UTC
Labels: bug, priority-low

**Comment by mastacheata** [comment] 2016-07-19 18:21
LOL. I'm pretty sure it's fixed due to 910e1e0 :eyes:
