### ISSUE TITLE
History

### ISSUE THREAD

**Issue by mastacheata** [odin-public/RESTClient-APS#46] opened 2016-06-29 00:10 UTC
This one's a feature I use quite often in the Chrome pendant "Advanced Rest Client".
It keeps track of the last 20 or so requests you made and you can bring them back, just like the bookmarks feature does at the moment.
Not sure how to implement that yet without reinventing the wheel. This is probably a good use case for tags or categories or labels.
I was thinking of having a prefs store with history elements and as soon as the maximum is reached, we pop one off at the end and add a new one in front, so this behaves like a queue with limited positions.

**Comment by mastacheata** [comment] 2016-06-29 00:14
Apparently there already is SOME history tracking, but sadly only the URL is kept and everything else seems to be discarded.

**Comment by gear54rus** [comment] 2016-07-04 11:22
> Apparently there already is SOME history tracking, but sadly only the URL is kept and everything else seems to be discarded.

Before I look at that pull, can we get some steps to reproduce the 'only URL is kept' part? It works pretty well for me: https://i.imgur.com/YI6CpdC.gifv

**Comment by mastacheata** [comment] 2016-07-04 12:26
I mixed up the "cached" Request (the one in the star arrow-down thing next to the URL, which apparently only tracks the URL) with the history functionality.
The cached request is actually just the cached URL of the latest bookmark you create. (I don't have any use for that)

What I think is lacking with the current history tracking is that there is no way to access the history anymore once you close the Addon's tab. As Firefox doesn't track the history of chrome:// URLs, there's no way to restore old requests you made before.

This seems to be the working habit for me and my colleagues at least.
We're building a web application with traditional Frontend/Backend separation where the backend provides a semi-public REST API to the frontend.
We're not doing work in the REST client(s) all the time, but it's an incredibly useful tool for debugging some harder issues.
I know I could create bookmarks for all the requests, but usually I rarely have any identical requests and want to change some parameters here and there. As this is usually happening gradually (adding/removing stuff by trial and error) I'd love to see my last attempt(s) when returning to the REST Client.

I really like how the "Advanced REST Client" for Chrome solved this. (It's been an addon for a few years, but now it's a standalone Chrome app)

**Comment by gear54rus** [comment] 2016-07-13 12:03
I looked at the build and understood that we're in dire need of changing the bookmark UI. It should reflect request headers and other stuff, and should maybe reflect cURL representation, but token cURL is useless. I'll change the bookmarks look and then I would really like you to achieve the same look with history if you can to be consistent.

Also when are old entries removed? How are too-long strings handled?

**Comment by mastacheata** [comment] 2016-07-14 19:31
Sure, I'll go with everything you make.

I don't think old entries are ever removed. There's functionality for removing a single entry or entries older than X days, but it doesn't look like it's ever used. I didn't write that part, though. It was already there before and I only built a GUI to access it.

**Comment by gear54rus** [comment] 2016-07-20 04:47
ok so I've revamped the UI a bit. I've changed the layout of menus and merged `Bookmarks` and `History` top buttons into a single `Saved Requests` button since this is a similar functionality. This menu contains 2 categories that were top buttons previously.

Please look at the new bookmarks template and adjust the history template to match it. Also, please make sure that associated functions (like history removal button code) are working properly for history, *they may contain selectors that will match bookmarks UI accidentally*.

I'll push the aforementioned commits and will work on the history auto-clear meanwhile...

**Comment by gear54rus** [comment] 2016-07-20 06:06
Not really closed, idk why it thought that it is..

**Comment by gear54rus** [comment] 2016-07-20 06:33
Another important point: we aren't updating `lastAccess` for a history item when we restore it. This needs to be fixed or  history items will get deleted after 30 days pass since their creation, not since their last touch.

This has to be added to restoration buttons in your UI or somewhere around that.

**Comment by gear54rus** [comment] 2016-07-20 09:11
Auto-removal is implemented in 968e4cf4c955848ff090c6a16cabcf1369a94057.

**Comment by gear54rus** [comment] 2016-07-22 09:30
@mastacheata any news on this?

**Comment by mastacheata** [comment] 2016-07-22 09:45
Sorry, completely missed the notifications before. 
I'm abroad over the weekend, but I'll go for it on Monday.

**Comment by gear54rus** [comment] 2016-07-28 02:18
@mastacheata did your plans change on this?

**Comment by mastacheata** [comment] 2016-07-29 14:10
Not my plans, but reality overtook my plans faster than I could imagine :fearful: 
Not sure when I will get to this. I promise to get this done as fast as possible, but without any specific timeframe yet.

**Comment by mastacheata** [comment] 2016-08-02 19:28
It just came to my mind that we could use a clear history button.

**Comment by gear54rus** [comment] 2016-08-04 04:15
@mastacheata Added it. It seems we're done with this issue. Anything else you want to see in 1.9 or should I push it?

I also decided to forego touching the history items when we restore them. User can just try to send that request again, it will push it up to the top of history.

**Comment by mastacheata** [comment] 2016-08-04 05:35
Do we need a clear history button along with a truncate query for the history table? 
I don't really need that myself, but maybe you got a use case where one wants to forget the whole history at once? 
-- 
Gruß, 
Benedikt Bauer 

Am 4. August 2016 06:15:59 MESZ, schrieb Paul <notifications@github.com>:

**Comment by gear54rus** [comment] 2016-08-04 05:50
> Do we need a clear history button along with a truncate query for the history table?

It's too late to ask, it's in the latest commit like I said :)

**Comment by mastacheata** [comment] 2016-08-04 08:56
Hahaha, sorry missed that. 
-- 
Gruß, 
Benedikt Bauer 

Am 4. August 2016 07:50:12 MESZ, schrieb Paul <notifications@github.com>:

**Comment by gear54rus** [comment] 2016-08-04 09:03
@mastacheata did you test the latest build? Anything you want to include before 1.9 gets pushed out?

**Comment by mastacheata** [comment] 2016-08-04 09:22
Not yet, but everything I was wished for is already in, thanks. 
-- 
Gruß, 
Benedikt Bauer 

Am 4. August 2016 11:03:34 MESZ, schrieb Paul <notifications@github.com>:

**Closed** 2016-08-05 08:54 UTC
Labels: enhancement, priority-low
