### ISSUE TITLE
Edit bookmark

### ISSUE THREAD

**Issue by mirkoperillo** [odin-public/RESTClient-APS#40] opened 2016-05-27 15:03 UTC
It's impossible to edit a bookmark.

So If a restore a previously saved bookmark and I change it I cannot override the same bookmark.

There isn't a _save modification_ button and if I bookmark the edited request given it the same name, it isn't override but it's created a new bookmark with the same name.

**Comment by gear54rus** [comment] 2016-06-02 06:53
This appears to be not intended by extensions creator. Here you can see that UUID is used as means to determine if the _saved request_ (aka **bookmark**) are the same or not. Yet, this UUID is generated randomly each time and name has no bearing on whether requests are the same or not.

![0hhtkhu](https://cloud.githubusercontent.com/assets/8073599/15736190/dfd85c0c-28bf-11e6-9317-3f7862ac27b7.png)

To implement this at least 2 things are needed:

- Add `UPDATE` query to SQLite query storage for this scenario. Currently, only `INSERT` exists, one more reason this scenario was not intended to work originally.
- Make saved requests be differentiated by name instead of UUIDs.

This goes into `help wanted` category due to being minor and not a bug.

**Comment by gear54rus** [comment] 2017-07-25 11:10
Fixed in 6d10f9a.

**Closed by gear54rus** 2017-07-25 11:10 UTC
Labels: enhancement, help wanted, priority-low
